# This is a very simple script to instantiate e 
# Apache Kafka + Flink cluster (please note you have to
# specify 'localhost' for kafka inside your source)

version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.220.244.218 # change to match hostname
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flink-master:
     image: bde2020/flink-master
     hostname: flink-master
     container_name: flink-master
     environment:
        - INIT_DAEMON_STEP=setup_flink
  #     - "constraint:node==<yourmasternode>"
     ports:
       - "8080:8080"
       - "8081:8081"
     mem_limit: 2g

  flink-worker:
    image: bde2020/flink-worker
    hostname: flink-worker
    container_name: flink-worker
    environment:
       - "FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master"
  #    - "constraint:node==<yourworkernode>"
    depends_on:
      - "flink-master"
    mem_limit: 2g

