version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka.project-ember.city
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  flink-jobmanager:
      image: melentye/flink:1.2.0
      ports:
        - "8081:8081"
      expose:
        - "6123"
      command: jobmanager

   flink-taskmanager:
      image: melentye/flink:1.2.0
      expose:
        - "6121"
        - "6122"
      depends_on:
        - flink-jobmanager
      links:
        - flink-jobmanager
      command: taskmanager

