package it.uniroma2.ember.utils;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;

/**
 * Implements a simple object to represent the alert generated by monitoring system
 */

public class Alert {

    public static final String ERROR_SENT   = "[ lost connection with lamp, electrical failure ]";
    public static final String ERROR_EXPIRE = "[ lamp is out of expiration safety limits ]";
    public static final String ERROR_LEVEL  = "[ lamp is operating out of safety level bounds ]";

    private int id;
    private String address;
    private String model;
    private String message;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Alert() { /* */ }

    public Alert(int id, String address, String model, String message) {
        this.id = id;
        this.address = address;
        this.model = model;
        this.message = message;
    }

    public static String serializeAlert(Alert alert) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        return mapper.writeValueAsString(alert);

    }
}
